#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x12(
		LT(2,KC_TAB),	KC_Q, 		KC_W, 	KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, 	KC_O, 	KC_P, 		KC_BSLS,
		LCTL_T(KC_ESC), KC_A, 		KC_S, 	KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, 	KC_L, 	KC_SCLN,	KC_QUOT,
		KC_LSPO, 		KC_Z, 		KC_X,	KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM,KC_DOT, KC_SLSH, 	KC_RSPC,
		MO(1), 			KC_GRV, 	KC_EQL, KC_LALT, KC_SPC, KC_LGUI, KC_BSPC, KC_ENT, KC_RGUI, KC_RALT, KC_MINS, MO(1)),

	[1] = LAYOUT_ortho_4x12(
		LCAG(KC_SPC), 	KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
		_______, _______, _______, _______, _______, _______, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_BRID, KC_BRIU, LSFT_T(KC_LBRC), _______, _______, _______, _______, _______, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, KC_MUTE, RSFT_T(KC_RBRC), KC_TRNS, KC_LSFT, _______, _______, KC_MPLY, _______, _______, KC_ENT, _______, _______, KC_RSFT, KC_TRNS),
	[2] = LAYOUT_ortho_4x12(_______, KC_ACL0, KC_ACL1, KC_ACL2, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, BL_TOGG, _______, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, RGB_TOG, _______, _______, _______, _______, _______, RGB_TOG, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_BTN1, KC_BTN2, _______, _______, _______, _______, _______)
};

